using System;
using System.Linq;
using StarkBank.Utils;
using System.Collections.Generic;

namespace StarkBank
{
    /// <summary>
    /// Split object
    /// <br/>
    /// The Split resource is used to split an Invoice or Boleto between different receivers.
    /// <br/>
    /// Properties:
    /// <list>
    ///     <item>Amount [long integer]: value to send to receivers in cents. ex: 1000 (= R$ 10.00)</item>
    ///     <item>ReceiverID [string]: split receiver unique id. ex: "5656565656565656"</item>
    ///     <item>ID [long integer]: split unique id. ex: 1234567890</item>
    ///     <item>Source [string]: source receivable which generated this split object. ex: "5656565656565656"</item>
    ///     <item>ExternalID [string]: unique id, generated by the system, to avoid duplicated splits. ex: "invoice/1234/receiver/5678"
    ///     <item>Tags [list of strings, default null]: list of strings for tagging</item>
    ///     <item>Scheduled [DateTime, default now]: payment scheduled date or datetime. ex: new DateTime(2020, 3, 10, 15, 17, 3)</item>
    ///     <item>Status [string]: current payment status. ex: "success" or "failed"</item>
    ///     <item>Created [DateTime]: creation datetime for the payment. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
    ///     <item>Updated [DateTime]: update datetime for the payment. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
    /// </list>
    /// </summary>
    public partial class Split : Resource
    {
        public long Amount { get; }
        public string ReceiverID { get; }
        public string Source { get; }
        public string ExternalID { get; }
        public List<string> Tags { get; }
        public DateTime? Scheduled { get; }
        public string Status { get; }
        public DateTime? Created { get; }
        public DateTime? Updated { get; }

        /// <summary>
        /// Split object
        /// <br/>
        /// The Split resource is used to split an Invoice or Boleto between different receivers.
        /// <br/>
        /// Attributes (return-only):
        /// <list>
        ///     <item>amount [long integer]: value to send to receivers in cents. ex: 1000 (= R$ 10.00)</item>
        ///     <item>receiverID [string]: split receiver unique id. ex: "5656565656565656"</item>
        ///     <item>id [string]: split unique id. ex: "5656565656565656"</item>
        ///     <item>source [string]: source receivable which generated this split object. ex: "5656565656565656"</item>
        ///     <item>externalID [string]: unique id, generated by the system, to avoid duplicated splits. ex: "invoice/1234/receiver/5678"</item>
        ///     <item>tags [list of strings, default null]: list of strings for tagging</item>
        ///     <item>scheduled [DateTime, default now]: payment scheduled date or datetime. ex: new DateTime(2020, 3, 10, 15, 17, 3)</item>
        ///     <item>status [string]: current payment status. ex: "success" or "failed"</item>
        ///     <item>created [DateTime]: creation datetime for the payment. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        ///     <item>updated [DateTime]: update datetime for the payment. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public Split(long amount, string receiverID, string source = null, string externalID = null,
            List<string> tags = null, DateTime? scheduled = null, string status = null, DateTime? created = null,
            DateTime? updated = null, string id = null) : base(id)
        {
            Amount = amount;
            ReceiverID = receiverID;
            Source = source;
            ExternalID = externalID;
            Tags = tags;
            Scheduled = scheduled;
            Status = status;
            Created = created;
            Updated = updated;
        }

        internal new Dictionary<string, object> ToJson()
        {
            Dictionary<string, object> json = base.ToJson();
            return json;
        }

        /// <summary>
        /// Retrieve a specific Split
        /// <br/>
        /// Receive a single Split object previously created in the Stark Bank API by passing its id
        /// <br/>
        /// Parameters(required):
        /// <list>
        ///     <item>id[string]: object unique id. ex: "5656565656565656"</item>
        /// </list>
        /// <br/>
        /// Parameters(optional):
        /// <list>
        ///     <item>user[Project object]: Project object. Not necessary if StarkBank.User.Default was set before function call</item>
        /// </list>
        /// <br/>
        /// Return:
        /// <list>
        ///     <item>Split object with updated attributes</item>
        /// </list>
        /// </summary>
        public static Split Get(string id, User user = null)
        {
            (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
            return Rest.GetId(
                resourceName: resourceName,
                resourceMaker: resourceMaker,
                id: id,
                user: user
            ) as Split;
        }

        /// <summary>
        /// Retrieve Splits
        /// <br/>
        /// Receive an IEnumerable of Split objects previously created in the Stark Bank API
        /// <br/>
        /// Parameters (optional):
        /// <list>
        ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
        ///     <item>after [DateTime, default null]: date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
        ///     <item>before [DateTime, default null]: date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
        ///     <item>status [list of strings, default null]: filter for status of retrieved objects. ex: ["created", "success"]</item>
        ///     <item>tags [list of strings, default null]: tags to filter retrieved objects. ex: ["tony", "stark"]</item>
        ///     <item>ids [list of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]</item>
        ///     <item>receiverIds [list of strings, default null]: list of receiver ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]</item>
        ///     <item>user [Project object, default null]: Project object. Not necessary if StarkBank.User.Default was set before function call</item>
        /// </list>
        /// <br/>
        /// Return:
        /// <list>
        ///     <item>IEnumerable of Split objects with updated attributes</item>
        /// </list>
        /// </summary>
        public static IEnumerable<Split> Query(int? limit = null, DateTime? after = null, DateTime? before = null,
            List<string> status = null, List<string> tags = null, List<string> ids = null, List<string> receiverIds = null, User user = null)
        {
            (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
            return Rest.GetList(
                resourceName: resourceName,
                resourceMaker: resourceMaker,
                query: new Dictionary<string, object> {
                    { "limit", limit },
                    { "after", new StarkCore.Utils.StarkDate(after) },
                    { "before", new StarkCore.Utils.StarkDate(before) },
                    { "status", status },
                    { "tags", tags },
                    { "ids", ids },
                    { "receiverIds", receiverIds }
                },
                user: user
            ).Cast<Split>();
        }

        /// <summary>
        /// Retrieve paged Splits
        /// <br/>
        /// Receive a list of up to 100 Split objects previously created in the Stark Bank API and the cursor to the next page.
        /// Use this function instead of query if you want to manually page your requests.
        /// <br/>
        /// Parameters (optional):
        /// <list>
        ///     <item>cursor [string, default null]: cursor returned on the previous page function call</item>
        ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
        ///     <item>after [DateTime, default null]: date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
        ///     <item>before [DateTime, default null]: date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
        ///     <item>status [list of strings, default null]: filter for status of retrieved objects. ex: ["created", "success"]</item>
        ///     <item>tags [list of strings, default null]: tags to filter retrieved objects. ex: ["tony", "stark"]</item>
        ///     <item>receiverIds [list of strings, default null]: list of receiver ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]</item>
        ///     <item>ids [list of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]</item>
        ///     <item>user [Project object, default null]: Project object. Not necessary if StarkBank.User.Default was set before function call</item>
        /// </list>
        /// <br/>
        /// Return:
        /// <list>
        ///     <item>list of Split objects with updated attributes and cursor to retrieve the next page of Split objects</item>
        /// </list>
        /// </summary>
        public static (List<Split> page, string pageCursor) Page(string cursor = null, int? limit = null, DateTime? after = null,
            DateTime? before = null, List<string> status = null, List<string> tags = null, List<string> ids = null, List<string> receiverIds = null, User user = null)
        {
            (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) = Resource();
            (List<StarkCore.Utils.SubResource> page, string pageCursor) = Rest.GetPage(
                resourceName: resourceName,
                resourceMaker: resourceMaker,
                query: new Dictionary<string, object> {
                    { "cursor", cursor },
                    { "limit", limit },
                    { "after", new StarkCore.Utils.StarkDate(after) },
                    { "before", new StarkCore.Utils.StarkDate(before) },
                    { "status", status },
                    { "tags", tags },
                    { "receiverIds", receiverIds },
                    { "ids", ids },
                },
                user: user
            );
            List<Split> splits = new List<Split>();
            foreach (StarkCore.Utils.SubResource subResource in page)
            {
                splits.Add(subResource as Split);
            }
            return (splits, pageCursor);
        }

        internal static (string resourceName, StarkCore.Utils.Api.ResourceMaker resourceMaker) Resource()
        {
            return (resourceName: "Split", resourceMaker: ResourceMaker);
        }

        internal static Resource ResourceMaker(dynamic json)
        {
            long amount = json.amount;
            string receiverID = json.receiverId;
            string source = json.source;
            string externalID = json.externalId;
            List<string> tags = json.tags?.ToObject<List<string>>();
            DateTime? scheduled = json.scheduled;
            string status = json.status;
            DateTime? created = json.created;
            DateTime? updated = json.updated;
            string id = json.id;

            return new Split(
                amount: amount, receiverID: receiverID, source: source, externalID: externalID, tags: tags,
                scheduled: scheduled, status: status, created: created, updated: updated, id: id
            );
        }
    }
}