using System;
using System.Linq;
using System.Collections.Generic;


namespace StarkBank
{
    public partial class UtilityPayment
    {
        /// <summary>
        /// UtilityPayment.Log object
        /// <br/>
        /// Every time a UtilityPayment entity is modified, a corresponding UtilityPayment.Log
        /// is generated for the entity. This log is never generated by the user, but it can
        /// be retrieved to check additional information on the UtilityPayment.
        /// <br/>
        /// Properties:
        /// <list>
        ///     <item>ID [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
        ///     <item>Payment [UtilityPayment]: UtilityPayment entity to which the log refers to.</item>
        ///     <item>Errors [list of strings]: list of errors linked to this BoletoPayment event.</item>
        ///     <item>Type [string]: type of the UtilityPayment event which triggered the log creation. ex: "registered" or "paid"</item>
        ///     <item>Created [DateTime]: creation datetime for the payment. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public class Log : Utils.Resource
        {
            public DateTime Created { get; }
            public string Type { get; }
            public List<string> Errors { get; }
            public UtilityPayment Payment { get; }

            /// <summary>
            /// UtilityPayment.Log object
            /// <br/>
            /// Every time a UtilityPayment entity is modified, a corresponding UtilityPayment.Log
            /// is generated for the entity. This log is never generated by the user, but it can
            /// be retrieved to check additional information on the UtilityPayment.
            /// <br/>
            /// Attributes:
            /// <list>
            ///     <item>id [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
            ///     <item>payment [UtilityPayment]: UtilityPayment entity to which the log refers to.</item>
            ///     <item>errors [list of strings]: list of errors linked to this BoletoPayment event.</item>
            ///     <item>type [string]: type of the UtilityPayment event which triggered the log creation. ex: "registered" or "paid"</item>
            ///     <item>created [DateTime]: creation datetime for the payment. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)</item>
            /// </list>
            /// </summary>
            public Log(string id, DateTime created, string type, List<string> errors, UtilityPayment payment) : base(id)
            {
                Created = created;
                Type = type;
                Errors = errors;
                Payment = payment;
            }

            /// <summary>
            /// Retrieve a specific Log
            /// <br/>
            /// Receive a single Log object previously created by the Stark Bank API by passing its id
            /// <br/>
            /// Parameters (required):
            /// <list>
            ///     <item>id [string]: object unique id. ex: "5656565656565656"</item>
            /// </list>
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>user [Project object]: Project object. Not necessary if StarkBank.User.Default was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>Log object with updated attributes</item>
            /// </list>
            /// </summary>
            public static Log Get(string id, User user = null)
            {
                (string resourceName, Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Utils.Rest.GetId(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    id: id,
                    user: user
                ) as Log;
            }

            /// <summary>
            /// Retrieve Logs
            /// <br/>
            /// Receive an IEnumerable of Log objects previously created in the Stark Bank API
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35</item>
            ///     <item>paymentIds [list of strings, default nil]: list of UtilityPayment ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]</item>
            ///     <item>types [list of strings, default nil]: filter retrieved objects by event types. ex: "paid" or "registered"</item>
            ///     <item>user [Project object, default nil]: Project object. Not necessary if StarkBank.User.Default was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>list of Log objects with updated attributes</item>
            /// </list>
            /// </summary>
            public static IEnumerable<Log> Query(int? limit = null, List<string> paymentIds = null, List<string> types = null,
                User user = null)
            {
                (string resourceName, Utils.Api.ResourceMaker resourceMaker) = Resource();
                return Utils.Rest.GetList(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "limit", limit },
                        { "paymentIds", paymentIds },
                        { "types", types }
                    },
                    user: user
                ).Cast<Log>();
            }

            internal static (string resourceName, Utils.Api.ResourceMaker resourceMaker) Resource()
            {
                return (resourceName: "UtilityPaymentLog", resourceMaker: ResourceMaker);
            }

            internal static Utils.Resource ResourceMaker(dynamic json)
            {
                List<string> errors = json.errors.ToObject<List<string>>();
                string id = json.id;
                string createdString = json.created;
                DateTime created = Utils.Checks.CheckDateTime(createdString);
                string type = json.type;
                UtilityPayment payment = UtilityPayment.ResourceMaker(json.payment);

                return new Log(id: id, created: created, type: type, errors: errors, payment: payment);
            }
        }
    }
}
