using System;
using System.Linq;
using System.Collections.Generic;
using StarkBank.Utils;
using System.Diagnostics;


namespace StarkBank
{
    public partial class CorporatePurchase
    {
        /// <summary>
        /// CorporatePurchase.Log object
        /// <br/>
        /// Every time a CorporatePurchase entity is modified, a corresponding CorporatePurchase.Log
        /// is generated for the entity. This log is never generated by the
        /// user.
        /// <br/>
        /// Properties:
        /// <list>
        ///     <item>ID[string]: unique id returned when the log is created. ex: "5656565656565656"</item>
        ///     <item>Purchase [CorporatePurchase]: CorporatePurchase entity to which the log refers to.</item>
        ///     <item>Description [string]: purchase descriptions. ex: "my_description"</item>
        ///     <item>CorporateTransactionID [string]: transaction ID related to the CorporateCard.</item>
        ///     <item>Errors [list of strings]: list of errors linked to this CorporatePurchase event.</item>
        ///     <item>Type [string]: type of the CorporatePurchase event which triggered the log creation. ex: "approved", "canceled", "confirmed", "denied", "reversed" and "voided"</item>
        ///     <item>Created [DateTime]: creation DateTime for the log. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
        /// </list>
        /// </summary>
        public class Log : Resource
        {
            public CorporatePurchase Purchase { get; }
            public string Description { get; }
            public string CorporateTransactionID { get; }
            public string Type { get; }
            public List<Dictionary<string, object>> Errors { get; }
            public DateTime Created { get; }

            /// <summary>
            /// CorporatePurchase.Log object
            /// <br/>
            /// Every time a CorporatePurchase entity is modified, a corresponding CorporatePurchase.Log
            /// is generated for the entity. This log is never generated by the
            /// user.
            /// <br/>
            /// Attributes (return-only):
            /// <list>
            ///     <item>id [string]: unique id returned when the log is created. ex: "5656565656565656"</item>
            ///     <item>type [string]: type of the CorporatePurchase event which triggered the log creation. ex: "approved", "canceled", "confirmed", "denied", "reversed" and "voided"</item>
            ///     <item>purchase [CorporatePurchase]: CorporatePurchase entity to which the log refers to.</item>
            ///     <item>description [string]: purchase descriptions. ex: "my_description"</item>
            ///     <item>corporateTransactionID [string]: transaction ID related to the CorporateCard.</item>
            ///     <item>errors [list of strings]: list of errors linked to this CorporatePurchase event.</item>
            ///     <item>created [DateTime]: creation DateTime for the log. ex: new DateTime(2020, 3, 10, 10, 30, 0, 0)</item>
            /// </list>
            /// </summary>
            public Log(
                string id,
                string type,
                CorporatePurchase purchase,
                string description,
                List<Dictionary<string,object>> errors,
                DateTime created
            ) : base(id)
            {
                Created = created;
                Type = type;
                Errors = errors;
                Purchase = purchase;
                Description = description;
            }

            /// <summary>
            /// Retrieve a specific CorporatePurchase.Log
            /// <br/>
            /// Receive a single CorporatePurchase.Log object previously created by the Stark Infra API by passing its id
            /// <br/>
            /// Parameters (required):
            /// <list>
            ///     <item>id [string]: object unique id. ex: "5656565656565656"</item>
            /// </list>
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>Log object with updated attributes</item>
            /// </list>
            /// </summary>
            public static Log Get(string id, User user = null)
            {
                (string resourceName, Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetId(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    id: id,
                    user: user
                ) as Log;
            }

            /// <summary>
            /// Retrieve CorporatePurchase.Log objects
            /// <br/>
            /// Receive an IEnumerable of CorporatePurchase.Log objects previously created in the Stark Infra API
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35</item>
            ///     <item>after [DateTime, default null] date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null] date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "approved", "canceled", "confirmed", "denied", "reversed" and "voided" }</item>
            ///     <item>purchaseIds [list of strings, default null]: list of Purchase ids to filter logs. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>ids [list of strings, default null]: list of CorporatePurchase ids to filter logs. ex: new List<string>{"5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>IEnumerable of CorporatePurchase.Log objects with updated attributes</item>
            /// </list>
            /// </summary>
            public static IEnumerable<Log> Query(int? limit = null, DateTime? after = null, DateTime? before = null,
                List<string> types = null, List<string> purchaseIds = null, User user = null)
            {
                (string resourceName, Api.ResourceMaker resourceMaker) = Resource();
                return Rest.GetList(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "purchaseIds", purchaseIds }
                    },
                    user: user
                ).Cast<Log>();
            }

            /// <summary>
            /// Retrieve paged CorporatePurchase.Log objects
            /// <br/>
            /// Receive a list of up to 100 CorporatePurchase.Log objects previously created in the Stark Infra API and the cursor to the next page.
            /// Use this function instead of query if you want to manually page your purchases.
            /// <br/>
            /// Parameters (optional):
            /// <list>
            ///     <item>cursor [string, default null]: cursor returned on the previous page function call</item>
            ///     <item>limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35.</item>
            ///     <item>after [DateTime, default null] date filter for objects created only after specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>before [DateTime, default null] date filter for objects created only before specified date. ex: DateTime(2020, 3, 10)</item>
            ///     <item>types [list of strings, default null]: filter retrieved objects by types. ex: new List<string>{ "approved", "canceled", "confirmed", "denied", "reversed" and "voided" }</item>
            ///     <item>purchaseIds [list of strings, default null]: list of Purchase ids to filter logs. ex: new List<string>{ "5656565656565656", "4545454545454545" }</item>
            ///     <item>ids [list of strings, default null]: list of CorporatePurchase ids to filter logs. ex: new List<string>{"5656565656565656", "4545454545454545" }</item>
            ///     <item>user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank.Settings.User was set before function call</item>
            /// </list>
            /// <br/>
            /// Return:
            /// <list>
            ///     <item>list of CorporatePurchase.Log objects with updated attributes</item>
            ///     <item>cursor to retrieve the next page of CorporatePurchase.Log objects</item>
            /// </list>
            /// </summary>
            public static (List<Log> page, string pageCursor) Page(string cursor = null, int? limit = null, DateTime? after = null,
                DateTime? before = null, List<string> types = null, List<string> purchaseIds = null, User user = null)
            {
                (string resourceName, Api.ResourceMaker resourceMaker) = Resource();
                (List<SubResource> page, string pageCursor) = Rest.GetPage(
                    resourceName: resourceName,
                    resourceMaker: resourceMaker,
                    query: new Dictionary<string, object> {
                        { "cursor", cursor },
                        { "limit", limit },
                        { "after", new StarkDate(after) },
                        { "before", new StarkDate(before) },
                        { "types", types },
                        { "purchaseIds", purchaseIds }
                    },
                    user: user
                );
                List<Log> logs = new List<Log>();
                foreach (SubResource subResource in page)
                {
                    logs.Add(subResource as Log);
                }
                return (logs, pageCursor);
            }

            internal static (string resourceName, Api.ResourceMaker resourceMaker) Resource()
            {
                return (resourceName: "CorporatePurchaseLog", resourceMaker: ResourceMaker);
            }

            internal static Resource ResourceMaker(dynamic json)
            {
                List<Dictionary<string, object>> errors = json.errors.ToObject<List<Dictionary<string, object>>>();
                string id = json.id;
                string createdString = json.created;
                DateTime created = Checks.CheckDateTime(createdString);
                string description = json.description;
                string type = json.type;
                CorporatePurchase purchase = CorporatePurchase.ResourceMaker(json.purchase);

                return new Log(id: id, created: created, type: type, errors: errors, purchase: purchase, description: description);
            }
        }
    }
}
